[package]
name = "quartz-print-fmspc"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
repository.workspace = true
homepage.workspace = true
categories = ["command-line-utilities", "cryptography::cryptocurrencies", "hardware-support", "wasm"]
keywords = ["blockchain", "cosmos", "tendermint", "cycles", "quartz"]
readme = "README.md"
description = """
Convenience tool to print the FMSPC (Family-Model-Stepping-Platform-Custom) of the local SGX processor.
"""

[dependencies]
dcap-qvl = "0.1.0"
hex.workspace = true
serde_json.workspace = true
tokio.workspace = true
