[template]
description = "An functioning example of a quartz app"

ignore = [
    "target/",  
    "contracts/Cargo.lock",
    "contracts/target",
    "contracts/schema",
    "enclave/Cargo.lock",
    "enclave/target",
    "enclave/src/prost/*",
    "frontend/package-lock.json",
    "scripts/"
]