[package]
name = "cycles-sync"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords = ["blockchain", "cosmos", "tendermint", "cycles", "quartz"]
readme = "README.md"

[dependencies]
# external
async-trait.workspace = true
bip32.workspace = true
clap.workspace = true
displaydoc.workspace = true
ecies.workspace = true
hex.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
subtle-encoding.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
anyhow = { version = "*" }

# cosmos
cosmrs.workspace = true
cosmwasm-std.workspace = true

# quartz
cw-tee-mtcs.workspace = true
wasmd-client.workspace = true
mtcs-enclave.workspace = true

[dev-dependencies]
rand_core.workspace = true
